version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8101:8101
    volumes:
      - .:/code
    depends_on:
      - db
    env_file: .env
  db:
    image: postgres:12.6-alpine
    restart: always
    env_file: .pgenv
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - 54322:5432
