# Generated by Django 3.2.11 on 2022-01-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Houmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive_at', models.DateTimeField(auto_now=True)),
                ('departure_at', models.DateTimeField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('visited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_visited', to='locator.houmer')),
            ],
        ),
        migrations.AlterField(
            model_name='houmerlocation',
            name='houmerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locator.houmer'),
        ),
    ]
