# Generated by Django 3.2.11 on 2022-01-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0002_auto_20220126_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='houmerlocation',
            name='velocity_kmh',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
